#! /bin/bash
#
# Arguments:
#   $1: tag revision

rev=$1
shift

#docker volume create -o type=tmpfs -o device=tmpfs -o o=exec,nosuid,nodev tmp-${rev} || true
docker volume create hawc-install-${rev} || true

docker run --rm -ti --name hawc-ape-${rev} \
       --mount src=hawc-install-${rev},dst=/hawc/install \
       lukasnellen/hawcape:${rev} \
       $@
